/*
 * Taurus-PROTECT APIs
 * Taurus-PROTECT APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.taurushq.sdk.protect.openapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.taurushq.sdk.protect.openapi.model.TgvalidatordContractCall;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.taurushq.sdk.protect.openapi.JSON;

/**
 * GenericCreateContractEVMContract
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-10-24T17:07:27.988152+02:00[Europe/Zurich]", comments = "Generator version: 7.9.0")
public class GenericCreateContractEVMContract {
  public static final String SERIALIZED_NAME_BYTECODE = "bytecode";
  @SerializedName(SERIALIZED_NAME_BYTECODE)
  private byte[] bytecode;

  public static final String SERIALIZED_NAME_CONSTRUCTOR = "constructor";
  @SerializedName(SERIALIZED_NAME_CONSTRUCTOR)
  private TgvalidatordContractCall constructor;

  public GenericCreateContractEVMContract() {
  }

  public GenericCreateContractEVMContract bytecode(byte[] bytecode) {
    this.bytecode = bytecode;
    return this;
  }

  /**
   * Get bytecode
   * @return bytecode
   */
  @javax.annotation.Nullable
  public byte[] getBytecode() {
    return bytecode;
  }

  public void setBytecode(byte[] bytecode) {
    this.bytecode = bytecode;
  }


  public GenericCreateContractEVMContract constructor(TgvalidatordContractCall constructor) {
    this.constructor = constructor;
    return this;
  }

  /**
   * Get constructor
   * @return constructor
   */
  @javax.annotation.Nullable
  public TgvalidatordContractCall getConstructor() {
    return constructor;
  }

  public void setConstructor(TgvalidatordContractCall constructor) {
    this.constructor = constructor;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GenericCreateContractEVMContract genericCreateContractEVMContract = (GenericCreateContractEVMContract) o;
    return Arrays.equals(this.bytecode, genericCreateContractEVMContract.bytecode) &&
        Objects.equals(this.constructor, genericCreateContractEVMContract.constructor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(Arrays.hashCode(bytecode), constructor);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GenericCreateContractEVMContract {\n");
    sb.append("    bytecode: ").append(toIndentedString(bytecode)).append("\n");
    sb.append("    constructor: ").append(toIndentedString(constructor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("bytecode");
    openapiFields.add("constructor");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GenericCreateContractEVMContract
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GenericCreateContractEVMContract.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GenericCreateContractEVMContract is not found in the empty JSON string", GenericCreateContractEVMContract.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GenericCreateContractEVMContract.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GenericCreateContractEVMContract` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `constructor`
      if (jsonObj.get("constructor") != null && !jsonObj.get("constructor").isJsonNull()) {
        TgvalidatordContractCall.validateJsonElement(jsonObj.get("constructor"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GenericCreateContractEVMContract.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GenericCreateContractEVMContract' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GenericCreateContractEVMContract> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GenericCreateContractEVMContract.class));

       return (TypeAdapter<T>) new TypeAdapter<GenericCreateContractEVMContract>() {
           @Override
           public void write(JsonWriter out, GenericCreateContractEVMContract value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GenericCreateContractEVMContract read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GenericCreateContractEVMContract given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GenericCreateContractEVMContract
   * @throws IOException if the JSON string is invalid with respect to GenericCreateContractEVMContract
   */
  public static GenericCreateContractEVMContract fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GenericCreateContractEVMContract.class);
  }

  /**
   * Convert an instance of GenericCreateContractEVMContract to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

