/*
 * Taurus-PROTECT APIs
 * Taurus-PROTECT APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.taurushq.sdk.protect.openapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.taurushq.sdk.protect.openapi.JSON;

/**
 * The risk score of Chainalysis is between 0 (lowest risk, good) to 100 (highest risk, bad).
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-10-24T17:07:27.988152+02:00[Europe/Zurich]", comments = "Generator version: 7.9.0")
public class ScoreFilterChainalysisFilters {
  public static final String SERIALIZED_NAME_SCORE_GREATER = "scoreGreater";
  @SerializedName(SERIALIZED_NAME_SCORE_GREATER)
  private String scoreGreater;

  public ScoreFilterChainalysisFilters() {
  }

  public ScoreFilterChainalysisFilters scoreGreater(String scoreGreater) {
    this.scoreGreater = scoreGreater;
    return this;
  }

  /**
   * Filter addresses with a Chainalysis risk score above threshold.
   * @return scoreGreater
   */
  @javax.annotation.Nullable
  public String getScoreGreater() {
    return scoreGreater;
  }

  public void setScoreGreater(String scoreGreater) {
    this.scoreGreater = scoreGreater;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScoreFilterChainalysisFilters scoreFilterChainalysisFilters = (ScoreFilterChainalysisFilters) o;
    return Objects.equals(this.scoreGreater, scoreFilterChainalysisFilters.scoreGreater);
  }

  @Override
  public int hashCode() {
    return Objects.hash(scoreGreater);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScoreFilterChainalysisFilters {\n");
    sb.append("    scoreGreater: ").append(toIndentedString(scoreGreater)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("scoreGreater");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ScoreFilterChainalysisFilters
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ScoreFilterChainalysisFilters.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ScoreFilterChainalysisFilters is not found in the empty JSON string", ScoreFilterChainalysisFilters.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ScoreFilterChainalysisFilters.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ScoreFilterChainalysisFilters` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("scoreGreater") != null && !jsonObj.get("scoreGreater").isJsonNull()) && !jsonObj.get("scoreGreater").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `scoreGreater` to be a primitive type in the JSON string but got `%s`", jsonObj.get("scoreGreater").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ScoreFilterChainalysisFilters.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ScoreFilterChainalysisFilters' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ScoreFilterChainalysisFilters> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ScoreFilterChainalysisFilters.class));

       return (TypeAdapter<T>) new TypeAdapter<ScoreFilterChainalysisFilters>() {
           @Override
           public void write(JsonWriter out, ScoreFilterChainalysisFilters value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ScoreFilterChainalysisFilters read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ScoreFilterChainalysisFilters given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ScoreFilterChainalysisFilters
   * @throws IOException if the JSON string is invalid with respect to ScoreFilterChainalysisFilters
   */
  public static ScoreFilterChainalysisFilters fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ScoreFilterChainalysisFilters.class);
  }

  /**
   * Convert an instance of ScoreFilterChainalysisFilters to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

