/*
 * Taurus-PROTECT APIs
 * Taurus-PROTECT APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.taurushq.sdk.protect.openapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.taurushq.sdk.protect.openapi.JSON;

/**
 * TgvalidatordUniqueCurrencyFilter
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-10-24T17:07:27.988152+02:00[Europe/Zurich]", comments = "Generator version: 7.9.0")
public class TgvalidatordUniqueCurrencyFilter {
  public static final String SERIALIZED_NAME_BLOCKCHAIN = "blockchain";
  @SerializedName(SERIALIZED_NAME_BLOCKCHAIN)
  private String blockchain;

  public static final String SERIALIZED_NAME_NETWORK = "network";
  @SerializedName(SERIALIZED_NAME_NETWORK)
  private String network;

  public static final String SERIALIZED_NAME_TOKEN_CONTRACT_ADDRESS = "tokenContractAddress";
  @SerializedName(SERIALIZED_NAME_TOKEN_CONTRACT_ADDRESS)
  private String tokenContractAddress;

  public static final String SERIALIZED_NAME_TOKEN_I_D = "tokenID";
  @SerializedName(SERIALIZED_NAME_TOKEN_I_D)
  private String tokenID;

  public TgvalidatordUniqueCurrencyFilter() {
  }

  public TgvalidatordUniqueCurrencyFilter blockchain(String blockchain) {
    this.blockchain = blockchain;
    return this;
  }

  /**
   * Get blockchain
   * @return blockchain
   */
  @javax.annotation.Nonnull
  public String getBlockchain() {
    return blockchain;
  }

  public void setBlockchain(String blockchain) {
    this.blockchain = blockchain;
  }


  public TgvalidatordUniqueCurrencyFilter network(String network) {
    this.network = network;
    return this;
  }

  /**
   * Get network
   * @return network
   */
  @javax.annotation.Nonnull
  public String getNetwork() {
    return network;
  }

  public void setNetwork(String network) {
    this.network = network;
  }


  public TgvalidatordUniqueCurrencyFilter tokenContractAddress(String tokenContractAddress) {
    this.tokenContractAddress = tokenContractAddress;
    return this;
  }

  /**
   * If this parameter is set, the currency returned will be a token with the specified contract address. If not set, the currency returned will be the native currency of the blockchain.
   * @return tokenContractAddress
   */
  @javax.annotation.Nullable
  public String getTokenContractAddress() {
    return tokenContractAddress;
  }

  public void setTokenContractAddress(String tokenContractAddress) {
    this.tokenContractAddress = tokenContractAddress;
  }


  public TgvalidatordUniqueCurrencyFilter tokenID(String tokenID) {
    this.tokenID = tokenID;
    return this;
  }

  /**
   * For some blockchains (ex. ALGO, XTZ) a tokenContractAddress might contain multiple assets. The tokenID is used to differentiate between those assets. If not set, the currency returned won&#39;t have any tokenID defined.
   * @return tokenID
   */
  @javax.annotation.Nullable
  public String getTokenID() {
    return tokenID;
  }

  public void setTokenID(String tokenID) {
    this.tokenID = tokenID;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TgvalidatordUniqueCurrencyFilter tgvalidatordUniqueCurrencyFilter = (TgvalidatordUniqueCurrencyFilter) o;
    return Objects.equals(this.blockchain, tgvalidatordUniqueCurrencyFilter.blockchain) &&
        Objects.equals(this.network, tgvalidatordUniqueCurrencyFilter.network) &&
        Objects.equals(this.tokenContractAddress, tgvalidatordUniqueCurrencyFilter.tokenContractAddress) &&
        Objects.equals(this.tokenID, tgvalidatordUniqueCurrencyFilter.tokenID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(blockchain, network, tokenContractAddress, tokenID);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TgvalidatordUniqueCurrencyFilter {\n");
    sb.append("    blockchain: ").append(toIndentedString(blockchain)).append("\n");
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("    tokenContractAddress: ").append(toIndentedString(tokenContractAddress)).append("\n");
    sb.append("    tokenID: ").append(toIndentedString(tokenID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("blockchain");
    openapiFields.add("network");
    openapiFields.add("tokenContractAddress");
    openapiFields.add("tokenID");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("blockchain");
    openapiRequiredFields.add("network");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TgvalidatordUniqueCurrencyFilter
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TgvalidatordUniqueCurrencyFilter.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TgvalidatordUniqueCurrencyFilter is not found in the empty JSON string", TgvalidatordUniqueCurrencyFilter.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TgvalidatordUniqueCurrencyFilter.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TgvalidatordUniqueCurrencyFilter` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TgvalidatordUniqueCurrencyFilter.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("blockchain").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `blockchain` to be a primitive type in the JSON string but got `%s`", jsonObj.get("blockchain").toString()));
      }
      if (!jsonObj.get("network").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `network` to be a primitive type in the JSON string but got `%s`", jsonObj.get("network").toString()));
      }
      if ((jsonObj.get("tokenContractAddress") != null && !jsonObj.get("tokenContractAddress").isJsonNull()) && !jsonObj.get("tokenContractAddress").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tokenContractAddress` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tokenContractAddress").toString()));
      }
      if ((jsonObj.get("tokenID") != null && !jsonObj.get("tokenID").isJsonNull()) && !jsonObj.get("tokenID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tokenID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tokenID").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TgvalidatordUniqueCurrencyFilter.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TgvalidatordUniqueCurrencyFilter' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TgvalidatordUniqueCurrencyFilter> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TgvalidatordUniqueCurrencyFilter.class));

       return (TypeAdapter<T>) new TypeAdapter<TgvalidatordUniqueCurrencyFilter>() {
           @Override
           public void write(JsonWriter out, TgvalidatordUniqueCurrencyFilter value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TgvalidatordUniqueCurrencyFilter read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TgvalidatordUniqueCurrencyFilter given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TgvalidatordUniqueCurrencyFilter
   * @throws IOException if the JSON string is invalid with respect to TgvalidatordUniqueCurrencyFilter
   */
  public static TgvalidatordUniqueCurrencyFilter fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TgvalidatordUniqueCurrencyFilter.class);
  }

  /**
   * Convert an instance of TgvalidatordUniqueCurrencyFilter to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

