/*
 * Taurus-PROTECT APIs
 * Taurus-PROTECT APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.taurushq.sdk.protect.openapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.taurushq.sdk.protect.openapi.JSON;

/**
 * TgvalidatordCreateOutgoingADADelegateRequestRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-10-24T17:07:27.988152+02:00[Europe/Zurich]", comments = "Generator version: 7.9.0")
public class TgvalidatordCreateOutgoingADADelegateRequestRequest {
  public static final String SERIALIZED_NAME_FROM_ADDRESS_ID = "fromAddressId";
  @SerializedName(SERIALIZED_NAME_FROM_ADDRESS_ID)
  private String fromAddressId;

  public static final String SERIALIZED_NAME_TO_STAKE_POOL_ADDRESS_ID = "toStakePoolAddressId";
  @SerializedName(SERIALIZED_NAME_TO_STAKE_POOL_ADDRESS_ID)
  private String toStakePoolAddressId;

  public static final String SERIALIZED_NAME_FEE_LIMIT = "feeLimit";
  @SerializedName(SERIALIZED_NAME_FEE_LIMIT)
  private String feeLimit;

  public static final String SERIALIZED_NAME_COMMENT = "comment";
  @SerializedName(SERIALIZED_NAME_COMMENT)
  private String comment;

  public static final String SERIALIZED_NAME_USE_UNCONFIRMED_FUNDS = "useUnconfirmedFunds";
  @SerializedName(SERIALIZED_NAME_USE_UNCONFIRMED_FUNDS)
  private Boolean useUnconfirmedFunds;

  public static final String SERIALIZED_NAME_TRANSACTION_REFERENCE = "transactionReference";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_REFERENCE)
  private String transactionReference;

  public static final String SERIALIZED_NAME_STAKE_POOL_REGISTRATION_CERTIFICATE = "stakePoolRegistrationCertificate";
  @SerializedName(SERIALIZED_NAME_STAKE_POOL_REGISTRATION_CERTIFICATE)
  private byte[] stakePoolRegistrationCertificate;

  public static final String SERIALIZED_NAME_STAKE_POOL_REGISTRATION_DEPOSIT = "stakePoolRegistrationDeposit";
  @SerializedName(SERIALIZED_NAME_STAKE_POOL_REGISTRATION_DEPOSIT)
  private Boolean stakePoolRegistrationDeposit;

  public static final String SERIALIZED_NAME_EXTERNAL_REQUEST_ID = "externalRequestId";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_REQUEST_ID)
  private String externalRequestId;

  public TgvalidatordCreateOutgoingADADelegateRequestRequest() {
  }

  public TgvalidatordCreateOutgoingADADelegateRequestRequest(
     byte[] stakePoolRegistrationCertificate, 
     Boolean stakePoolRegistrationDeposit
  ) {
    this();
    this.stakePoolRegistrationCertificate = stakePoolRegistrationCertificate;
    this.stakePoolRegistrationDeposit = stakePoolRegistrationDeposit;
  }

  public TgvalidatordCreateOutgoingADADelegateRequestRequest fromAddressId(String fromAddressId) {
    this.fromAddressId = fromAddressId;
    return this;
  }

  /**
   * Get fromAddressId
   * @return fromAddressId
   */
  @javax.annotation.Nonnull
  public String getFromAddressId() {
    return fromAddressId;
  }

  public void setFromAddressId(String fromAddressId) {
    this.fromAddressId = fromAddressId;
  }


  public TgvalidatordCreateOutgoingADADelegateRequestRequest toStakePoolAddressId(String toStakePoolAddressId) {
    this.toStakePoolAddressId = toStakePoolAddressId;
    return this;
  }

  /**
   * Get toStakePoolAddressId
   * @return toStakePoolAddressId
   */
  @javax.annotation.Nonnull
  public String getToStakePoolAddressId() {
    return toStakePoolAddressId;
  }

  public void setToStakePoolAddressId(String toStakePoolAddressId) {
    this.toStakePoolAddressId = toStakePoolAddressId;
  }


  public TgvalidatordCreateOutgoingADADelegateRequestRequest feeLimit(String feeLimit) {
    this.feeLimit = feeLimit;
    return this;
  }

  /**
   * Get feeLimit
   * @return feeLimit
   */
  @javax.annotation.Nullable
  public String getFeeLimit() {
    return feeLimit;
  }

  public void setFeeLimit(String feeLimit) {
    this.feeLimit = feeLimit;
  }


  public TgvalidatordCreateOutgoingADADelegateRequestRequest comment(String comment) {
    this.comment = comment;
    return this;
  }

  /**
   * Get comment
   * @return comment
   */
  @javax.annotation.Nullable
  public String getComment() {
    return comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }


  public TgvalidatordCreateOutgoingADADelegateRequestRequest useUnconfirmedFunds(Boolean useUnconfirmedFunds) {
    this.useUnconfirmedFunds = useUnconfirmedFunds;
    return this;
  }

  /**
   * Get useUnconfirmedFunds
   * @return useUnconfirmedFunds
   */
  @javax.annotation.Nullable
  public Boolean getUseUnconfirmedFunds() {
    return useUnconfirmedFunds;
  }

  public void setUseUnconfirmedFunds(Boolean useUnconfirmedFunds) {
    this.useUnconfirmedFunds = useUnconfirmedFunds;
  }


  public TgvalidatordCreateOutgoingADADelegateRequestRequest transactionReference(String transactionReference) {
    this.transactionReference = transactionReference;
    return this;
  }

  /**
   * DEPRECATED - use externalRequestId instead
   * @return transactionReference
   */
  @javax.annotation.Nullable
  public String getTransactionReference() {
    return transactionReference;
  }

  public void setTransactionReference(String transactionReference) {
    this.transactionReference = transactionReference;
  }


  /**
   * Get stakePoolRegistrationCertificate
   * @return stakePoolRegistrationCertificate
   */
  @javax.annotation.Nullable
  public byte[] getStakePoolRegistrationCertificate() {
    return stakePoolRegistrationCertificate;
  }



  /**
   * Get stakePoolRegistrationDeposit
   * @return stakePoolRegistrationDeposit
   */
  @javax.annotation.Nullable
  public Boolean getStakePoolRegistrationDeposit() {
    return stakePoolRegistrationDeposit;
  }



  public TgvalidatordCreateOutgoingADADelegateRequestRequest externalRequestId(String externalRequestId) {
    this.externalRequestId = externalRequestId;
    return this;
  }

  /**
   * Identifier for the request in the user&#39;s system. This must be unique. Attempting to create a request with an existing externalRequestId will do nothing and return the originally created request
   * @return externalRequestId
   */
  @javax.annotation.Nullable
  public String getExternalRequestId() {
    return externalRequestId;
  }

  public void setExternalRequestId(String externalRequestId) {
    this.externalRequestId = externalRequestId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TgvalidatordCreateOutgoingADADelegateRequestRequest tgvalidatordCreateOutgoingADADelegateRequestRequest = (TgvalidatordCreateOutgoingADADelegateRequestRequest) o;
    return Objects.equals(this.fromAddressId, tgvalidatordCreateOutgoingADADelegateRequestRequest.fromAddressId) &&
        Objects.equals(this.toStakePoolAddressId, tgvalidatordCreateOutgoingADADelegateRequestRequest.toStakePoolAddressId) &&
        Objects.equals(this.feeLimit, tgvalidatordCreateOutgoingADADelegateRequestRequest.feeLimit) &&
        Objects.equals(this.comment, tgvalidatordCreateOutgoingADADelegateRequestRequest.comment) &&
        Objects.equals(this.useUnconfirmedFunds, tgvalidatordCreateOutgoingADADelegateRequestRequest.useUnconfirmedFunds) &&
        Objects.equals(this.transactionReference, tgvalidatordCreateOutgoingADADelegateRequestRequest.transactionReference) &&
        Arrays.equals(this.stakePoolRegistrationCertificate, tgvalidatordCreateOutgoingADADelegateRequestRequest.stakePoolRegistrationCertificate) &&
        Objects.equals(this.stakePoolRegistrationDeposit, tgvalidatordCreateOutgoingADADelegateRequestRequest.stakePoolRegistrationDeposit) &&
        Objects.equals(this.externalRequestId, tgvalidatordCreateOutgoingADADelegateRequestRequest.externalRequestId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fromAddressId, toStakePoolAddressId, feeLimit, comment, useUnconfirmedFunds, transactionReference, Arrays.hashCode(stakePoolRegistrationCertificate), stakePoolRegistrationDeposit, externalRequestId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TgvalidatordCreateOutgoingADADelegateRequestRequest {\n");
    sb.append("    fromAddressId: ").append(toIndentedString(fromAddressId)).append("\n");
    sb.append("    toStakePoolAddressId: ").append(toIndentedString(toStakePoolAddressId)).append("\n");
    sb.append("    feeLimit: ").append(toIndentedString(feeLimit)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    useUnconfirmedFunds: ").append(toIndentedString(useUnconfirmedFunds)).append("\n");
    sb.append("    transactionReference: ").append(toIndentedString(transactionReference)).append("\n");
    sb.append("    stakePoolRegistrationCertificate: ").append(toIndentedString(stakePoolRegistrationCertificate)).append("\n");
    sb.append("    stakePoolRegistrationDeposit: ").append(toIndentedString(stakePoolRegistrationDeposit)).append("\n");
    sb.append("    externalRequestId: ").append(toIndentedString(externalRequestId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("fromAddressId");
    openapiFields.add("toStakePoolAddressId");
    openapiFields.add("feeLimit");
    openapiFields.add("comment");
    openapiFields.add("useUnconfirmedFunds");
    openapiFields.add("transactionReference");
    openapiFields.add("stakePoolRegistrationCertificate");
    openapiFields.add("stakePoolRegistrationDeposit");
    openapiFields.add("externalRequestId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("fromAddressId");
    openapiRequiredFields.add("toStakePoolAddressId");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TgvalidatordCreateOutgoingADADelegateRequestRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TgvalidatordCreateOutgoingADADelegateRequestRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TgvalidatordCreateOutgoingADADelegateRequestRequest is not found in the empty JSON string", TgvalidatordCreateOutgoingADADelegateRequestRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TgvalidatordCreateOutgoingADADelegateRequestRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TgvalidatordCreateOutgoingADADelegateRequestRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TgvalidatordCreateOutgoingADADelegateRequestRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("fromAddressId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `fromAddressId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fromAddressId").toString()));
      }
      if (!jsonObj.get("toStakePoolAddressId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `toStakePoolAddressId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("toStakePoolAddressId").toString()));
      }
      if ((jsonObj.get("feeLimit") != null && !jsonObj.get("feeLimit").isJsonNull()) && !jsonObj.get("feeLimit").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `feeLimit` to be a primitive type in the JSON string but got `%s`", jsonObj.get("feeLimit").toString()));
      }
      if ((jsonObj.get("comment") != null && !jsonObj.get("comment").isJsonNull()) && !jsonObj.get("comment").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `comment` to be a primitive type in the JSON string but got `%s`", jsonObj.get("comment").toString()));
      }
      if ((jsonObj.get("transactionReference") != null && !jsonObj.get("transactionReference").isJsonNull()) && !jsonObj.get("transactionReference").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `transactionReference` to be a primitive type in the JSON string but got `%s`", jsonObj.get("transactionReference").toString()));
      }
      if ((jsonObj.get("externalRequestId") != null && !jsonObj.get("externalRequestId").isJsonNull()) && !jsonObj.get("externalRequestId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `externalRequestId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("externalRequestId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TgvalidatordCreateOutgoingADADelegateRequestRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TgvalidatordCreateOutgoingADADelegateRequestRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TgvalidatordCreateOutgoingADADelegateRequestRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TgvalidatordCreateOutgoingADADelegateRequestRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<TgvalidatordCreateOutgoingADADelegateRequestRequest>() {
           @Override
           public void write(JsonWriter out, TgvalidatordCreateOutgoingADADelegateRequestRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TgvalidatordCreateOutgoingADADelegateRequestRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TgvalidatordCreateOutgoingADADelegateRequestRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TgvalidatordCreateOutgoingADADelegateRequestRequest
   * @throws IOException if the JSON string is invalid with respect to TgvalidatordCreateOutgoingADADelegateRequestRequest
   */
  public static TgvalidatordCreateOutgoingADADelegateRequestRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TgvalidatordCreateOutgoingADADelegateRequestRequest.class);
  }

  /**
   * Convert an instance of TgvalidatordCreateOutgoingADADelegateRequestRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

