/*
 * Taurus-PROTECT APIs
 * Taurus-PROTECT APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.taurushq.sdk.protect.openapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.taurushq.sdk.protect.openapi.model.TgvalidatordApproversGroup;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.taurushq.sdk.protect.openapi.JSON;

/**
 * TgvalidatordParallelApproversGroups
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-10-24T17:07:27.988152+02:00[Europe/Zurich]", comments = "Generator version: 7.9.0")
public class TgvalidatordParallelApproversGroups {
  public static final String SERIALIZED_NAME_SEQUENTIAL = "sequential";
  @SerializedName(SERIALIZED_NAME_SEQUENTIAL)
  private List<TgvalidatordApproversGroup> sequential = new ArrayList<>();

  public TgvalidatordParallelApproversGroups() {
  }

  public TgvalidatordParallelApproversGroups sequential(List<TgvalidatordApproversGroup> sequential) {
    this.sequential = sequential;
    return this;
  }

  public TgvalidatordParallelApproversGroups addSequentialItem(TgvalidatordApproversGroup sequentialItem) {
    if (this.sequential == null) {
      this.sequential = new ArrayList<>();
    }
    this.sequential.add(sequentialItem);
    return this;
  }

  /**
   * Get sequential
   * @return sequential
   */
  @javax.annotation.Nullable
  public List<TgvalidatordApproversGroup> getSequential() {
    return sequential;
  }

  public void setSequential(List<TgvalidatordApproversGroup> sequential) {
    this.sequential = sequential;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TgvalidatordParallelApproversGroups tgvalidatordParallelApproversGroups = (TgvalidatordParallelApproversGroups) o;
    return Objects.equals(this.sequential, tgvalidatordParallelApproversGroups.sequential);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sequential);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TgvalidatordParallelApproversGroups {\n");
    sb.append("    sequential: ").append(toIndentedString(sequential)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("sequential");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TgvalidatordParallelApproversGroups
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TgvalidatordParallelApproversGroups.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TgvalidatordParallelApproversGroups is not found in the empty JSON string", TgvalidatordParallelApproversGroups.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TgvalidatordParallelApproversGroups.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TgvalidatordParallelApproversGroups` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("sequential") != null && !jsonObj.get("sequential").isJsonNull()) {
        JsonArray jsonArraysequential = jsonObj.getAsJsonArray("sequential");
        if (jsonArraysequential != null) {
          // ensure the json data is an array
          if (!jsonObj.get("sequential").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `sequential` to be an array in the JSON string but got `%s`", jsonObj.get("sequential").toString()));
          }

          // validate the optional field `sequential` (array)
          for (int i = 0; i < jsonArraysequential.size(); i++) {
            TgvalidatordApproversGroup.validateJsonElement(jsonArraysequential.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TgvalidatordParallelApproversGroups.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TgvalidatordParallelApproversGroups' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TgvalidatordParallelApproversGroups> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TgvalidatordParallelApproversGroups.class));

       return (TypeAdapter<T>) new TypeAdapter<TgvalidatordParallelApproversGroups>() {
           @Override
           public void write(JsonWriter out, TgvalidatordParallelApproversGroups value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TgvalidatordParallelApproversGroups read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TgvalidatordParallelApproversGroups given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TgvalidatordParallelApproversGroups
   * @throws IOException if the JSON string is invalid with respect to TgvalidatordParallelApproversGroups
   */
  public static TgvalidatordParallelApproversGroups fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TgvalidatordParallelApproversGroups.class);
  }

  /**
   * Convert an instance of TgvalidatordParallelApproversGroups to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

