/*
 * Taurus-PROTECT APIs
 * Taurus-PROTECT APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.taurushq.sdk.protect.openapi.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets tgvalidatordChangeStatus
 */
@JsonAdapter(TgvalidatordChangeStatus.Adapter.class)
public enum TgvalidatordChangeStatus {
  
  CREATED("Created"),
  
  APPROVED("Approved"),
  
  REJECTED("Rejected"),
  
  CANCELED("Canceled");

  private String value;

  TgvalidatordChangeStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static TgvalidatordChangeStatus fromValue(String value) {
    for (TgvalidatordChangeStatus b : TgvalidatordChangeStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<TgvalidatordChangeStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final TgvalidatordChangeStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public TgvalidatordChangeStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return TgvalidatordChangeStatus.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    TgvalidatordChangeStatus.fromValue(value);
  }
}

